language: node_js
node_js:
- '5'
deploy:
  skip_cleanup: true
  provider: script
  script: "./deploy.sh"
  on:
    branch: master
    node: '5'
env:
  global:
  - secure: du7FzjEOIavaCuenxrYKykmSAp3pZaJNNfHS9zBiPp20a3YHMGGvhYBmJ36nuD/K7/7yWWmBhCDkcRuE0KDhP4OnWBNoELV0drCq7yu19w25napl83kVrAg2DyHnXqOcOSN93tuyahoGRuELvAvTpBmjF/sagARWeLAOSkkddNeedh6CoHw288Pv4si/Dcz0nzso/T+Ni5n1k5QJA1MC8ti1lHUi6Avy1Q8sVWxq0oa4uNicRgwTEFHgkiqB0xSiNZTliLoov+33drUAo7/5uz4l666Kg84bRReIw8t7yriQWKUNc2iJGTFKSNa+SxVnoLk1eO9cUWEG80qJbm8zHz5MCoRqzmtu98P1CEKapGJMij6GCFlZo6zhZw7K/w1BfHXC4PSNciEcunLtF5vudP7sJ1LqA5lENHHmor6Ygh4/aHfKP4KP0IJf6GiKbnrVKP2318oF8BOmm5YV+636NVi79IJwajYMYxXG2B+ETJFV/WaX7N+38pdJnPoJ0NeC+0Hoch1uZgra0WZBpYWJwLwc749BjxRty8mn2QAN1w+6d95TazxP0a0z+GvAR4Vgmc+NnSQLquqyZpMX9jL7uB9c7m8U6TbiSvjS4RAAdUAUJRIUQC0Hqk1afDstp4F9HVJcVcMYRXFojOKhqaGqXvLFQGYIzxf5+ZWkeCyISDY=
