language: node_js
node_js:
- '5'
deploy:
  skip_cleanup: true
  provider: script
  script: "./deploy.sh"
  on:
    branch: master
    node: '5'
before_install:
- openssl aes-256-cbc -K $encrypted_ed4710f1ea7e_key -iv $encrypted_ed4710f1ea7e_iv
  -in travis.enc -out travis -d
